Core was generated by `./segfault_gtk'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9c3e71afc2 in __memmove_sse2_unaligned_erms () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f9c3e645740 (LWP 965500))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.31-4.fc32.x86_64
(gdb) thread apply all bt full

Thread 8 (Thread 0x7f9c2d70a700 (LWP 965502)):
#0  0x00007f9c3e65ee92 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f9c2eab3a4b in blas_thread_server () from /home/stas/projects/nuitkas/wtf/segfault-gtk/segfault_gtk.dist/libopenblasp-r0-ae94cfde.3.9.dev.so
No symbol table info available.
#2  0x00007f9c3e658432 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007f9c3e772913 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 7 (Thread 0x7f9c23706700 (LWP 965506)):
#0  0x00007f9c3e65ee92 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f9c2eab3a4b in blas_thread_server () from /home/stas/projects/nuitkas/wtf/segfault-gtk/segfault_gtk.dist/libopenblasp-r0-ae94cfde.3.9.dev.so
No symbol table info available.
#2  0x00007f9c3e658432 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007f9c3e772913 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 6 (Thread 0x7f9c25f07700 (LWP 965505)):
#0  0x00007f9c3e65ee92 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f9c2eab3a4b in blas_thread_server () from /home/stas/projects/nuitkas/wtf/segfault-gtk/segfault_gtk.dist/libopenblasp-r0-ae94cfde.3.9.dev.so
No symbol table info available.
#2  0x00007f9c3e658432 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007f9c3e772913 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 5 (Thread 0x7f9c2df0b700 (LWP 965501)):
#0  0x00007f9c3e65ee92 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f9c2eab3a4b in blas_thread_server () from /home/stas/projects/nuitkas/wtf/segfault-gtk/segfault_gtk.dist/libopenblasp-r0-ae94cfde.3.9.dev.so
No symbol table info available.
#2  0x00007f9c3e658432 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007f9c3e772913 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 4 (Thread 0x7f9c20f05700 (LWP 965507)):
#0  0x00007f9c3e65ee92 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f9c2eab3a4b in blas_thread_server () from /home/stas/projects/nuitkas/wtf/segfault-gtk/segfault_gtk.dist/libopenblasp-r0-ae94cfde.3.9.dev.so
No symbol table info available.
#2  0x00007f9c3e658432 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007f9c3e772913 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7f9c28708700 (LWP 965504)):
--Type <RET> for more, q to quit, c to continue without paging--c
#0  0x00007f9c3e65ee92 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f9c2eab3a4b in blas_thread_server () from /home/stas/projects/nuitkas/wtf/segfault-gtk/segfault_gtk.dist/libopenblasp-r0-ae94cfde.3.9.dev.so
No symbol table info available.
#2  0x00007f9c3e658432 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007f9c3e772913 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7f9c2af09700 (LWP 965503)):
#0  0x00007f9c3e65ee92 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f9c2eab3a4b in blas_thread_server () from /home/stas/projects/nuitkas/wtf/segfault-gtk/segfault_gtk.dist/libopenblasp-r0-ae94cfde.3.9.dev.so
No symbol table info available.
#2  0x00007f9c3e658432 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007f9c3e772913 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7f9c3e645740 (LWP 965500)):
#0  0x00007f9c3e71afc2 in __memmove_sse2_unaligned_erms () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f9c30bbc56b in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>) at /usr/include/bits/string_fortified.h:34
No locals.
#2  png_write_row (png_ptr=png_ptr@entry=0x3301a70, row=<optimized out>) at pngwrite.c:842
        row_info = {width = 1920, rowbytes = 7680, color_type = 6 '\006', bit_depth = 8 '\b', channels = 4 '\004', pixel_depth = 32 ' '}
#3  0x00007f9c30bbc8cf in png_write_rows (png_ptr=0x3301a70, row=row@entry=0x7ffc88b2ae68, num_rows=num_rows@entry=1) at pngwrite.c:593
        i = 0
        rp = 0x7ffc88b2ae68
#4  0x00007f9c30bece98 in real_save_png (pixbuf=<optimized out>, keys=<optimized out>, values=<optimized out>, error=0x7ffc88b2b178, to_callback=to_callback@entry=1, f=f@entry=0x0, save_func=0x7f9c3ecce010, user_data=0x330aca0) at ../gdk-pixbuf/io-png.c:1162
        png_ptr = 0x3301a70
        info_ptr = 0x2f6b290
        text_ptr = 0x0
        ptr = 0x7f9c18f4b030 <error: Cannot access memory at address 0x7f9c18f4b030>
        pixels = 0x7f9c18f4b030 <error: Cannot access memory at address 0x7f9c18f4b030>
        y = 0
        i = <optimized out>
        row_ptr = 0x7f9c18f4b030 <error: Cannot access memory at address 0x7f9c18f4b030>
        sig_bit = {red = 8 '\b', green = 8 '\b', blue = 8 '\b', gray = 0 '\000', alpha = 8 '\b'}
        w = 1920
        h = 1200
        rowstride = 7680
        has_alpha = 1
        bpc = 8
        num_keys = 0
        compression = <optimized out>
        x_density = <optimized out>
        y_density = <optimized out>
        success = 1
        icc_profile = 0x0
        icc_profile_size = 0
        to_callback_ioptr = {save_func = 0x7f9c3ecce010, user_data = 0x330aca0, error = 0x7ffc88b2b178}
        __func__ = "real_save_png"
#5  0x00007f9c30bed43c in gdk_pixbuf__png_image_save_to_callback (save_func=<optimized out>, user_data=<optimized out>, pixbuf=<optimized out>, keys=<optimized out>, values=<optimized out>, error=<optimized out>) at ../gdk-pixbuf/io-png.c:1201
No locals.
#6  0x00007f9c30be09dd in gdk_pixbuf_real_save_to_callback (error=<optimized out>, values=0x3024450, keys=0x30242f0, type=0x3024330 "png", user_data=0x330aca0, save_func=0x7f9c3ecce010, pixbuf=0x2f4e240) at ../gdk-pixbuf/gdk-pixbuf-io.c:2382
        ret = <optimized out>
        image_module = 0x318cbb0
        ret = <optimized out>
        image_module = <optimized out>
#7  gdk_pixbuf_save_to_callbackv (pixbuf=0x2f4e240, save_func=0x7f9c3ecce010, user_data=0x330aca0, type=0x3024330 "png", option_keys=0x30242f0, option_values=0x3024450, error=0x7ffc88b2b178) at ../gdk-pixbuf/gdk-pixbuf-io.c:2709
        result = <optimized out>
        __func__ = "gdk_pixbuf_save_to_callbackv"
#8  0x00007f9c31137af0 in ffi_call_unix64 () at ../src/x86/unix64.S:76
No locals.
#9  0x00007f9c311372ab in ffi_call (cif=cif@entry=0x30243f8, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x7ffc88b2b0d8, avalue=<optimized out>) at ../src/x86/ffi64.c:525
        classes = {X86_64_INTEGER_CLASS, X86_64_NO_CLASS, 48696352, X86_64_NO_CLASS}
        stack = <optimized out>
        argp = 0x7ffc88b2af88 "\t"
        arg_types = <optimized out>
        gprcount = 6
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        ret_in_memory = <optimized out>
        reg_args = <optimized out>
#10 0x00007f9c31323f45 in pygi_invoke_c_callable (function_cache=0x3024350, state=<optimized out>, py_args=<optimized out>, py_kwargs=<optimized out>) at gi/pygi-invoke.c:684
        _save = 0x2e70c20
        cache = 0x3024350
        ffi_return_value = {v_boolean = 0, v_int8 = 0 '\000', v_uint8 = 0 '\000', v_int16 = 0, v_uint16 = 0, v_int32 = 0, v_uint32 = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_short = 0, v_ushort = 0, v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_ssize = 0, v_size = 0, v_string = 0x0, v_pointer = 0x0}
        ret = 0x0
#11 0x00007f9c3131aaec in pygi_function_cache_invoke (function_cache=<optimized out>, py_args=<optimized out>, py_kwargs=<optimized out>) at gi/pygi-cache.c:862
        state = {py_in_args = 0x7f9c1a0e1340, n_py_in_args = 6, n_args = 7, ffi_args = 0x330d0e0, args = 0x330d000, return_arg = {v_boolean = 0, v_int8 = 0 '\000', v_uint8 = 0 '\000', v_int16 = 0, v_uint16 = 0, v_int32 = 0, v_uint32 = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_short = 0, v_ushort = 0, v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_ssize = 0, v_size = 0, v_string = 0x0, v_pointer = 0x0}, to_py_return_arg_cleanup_data = 0x0, error = 0x0, failed = 0, user_data = 0x0, function_ptr = 0x7f9c30be07c0 <gdk_pixbuf_save_to_callbackv>}
#12 0x00007f9c31324699 in pygi_callable_info_invoke (user_data=0x0, cache=<optimized out>, kwargs=<optimized out>, py_args=<optimized out>, info=<optimized out>) at gi/pygi-invoke.c:764
No locals.
#13 _wrap_g_callable_info_invoke (self=<optimized out>, py_args=<optimized out>, kwargs=<optimized out>) at gi/pygi-invoke.c:764
No locals.
#14 0x00007f9c1a0eed50 in ?? ()
No symbol table info available.
#15 0x00007ffc88b2b250 in ?? ()
No symbol table info available.
#16 0x00007ffc88b2b300 in ?? ()
No symbol table info available.
#17 0x00007f9c313b1130 in ?? ()
No symbol table info available.
#18 0x00007f9c1a0ece70 in ?? ()
No symbol table info available.
#19 0x00000000004096a1 in CALL_FUNCTION (function_object=0x330e001, positional_args=0x7f9c18f4b030, named_args=<optimized out>) at /home/stas/.local/share/virtualenvs/segfault-gtk-caaKfl97/lib/python3.8/site-packages/nuitka/build/include/nuitka/calling.h:43
        call_slot = 0x330e001
        result = 0x7f9c3131e84d <_callable_info_call+141>
#20 0x000000000040aeb3 in CALL_FUNCTION_WITH_ARGS5 (called=0x7f9c1a0ece70, args=0x7ffc88b2b300) at __helpers.c:1457
        pos_args = <optimized out>
        result = 0x7ffc88b2b300
#21 0x0000000000411647 in impl___main__$$$function_2_save_pixbuf (self=0x330e001, python_pars=0x7f9c18f4b030) at module.__main__.c:1094
        call_args = {0x7f9c1b22de40, 0x7f9c1a0eed50, 0x7f9c313b4930, 0x7f9c1a10cac0, 0x7f9c1a10cbc0}
        tmp_called_name_3 = 0x7f9c1a0ece70
        tmp_closure_1 = {0x7f9c1a149340}
        tmp_args_element_name_2 = <optimized out>
        tmp_args_element_name_4 = <optimized out>
        tmp_assign_source_6 = 0x7f9c313b4930
        tmp_expression_name_3 = <optimized out>
        tmp_args_element_name_1 = <optimized out>
        tmp_args_element_name_3 = 0x7f9c313b4930
        tmp_args_element_name_5 = 0x7f9c3e834a40 <main_arena+96>
        par_pixbuf = <optimized out>
        par_filename = <optimized out>
        var_fp = 0x7f9c1a149340
        var_result = 0x7f9c313b4930
        tmp_with_1__enter = <optimized out>
        tmp_with_1__exit = <optimized out>
        tmp_with_1__indicator = <optimized out>
        tmp_with_1__source = <optimized out>
        frame_9f641251dfe286880f13a22251dc7153 = <optimized out>
        type_description_1 = <optimized out>
        exception_type = 0x0
        exception_value = 0x0
        exception_tb = 0x0
        exception_lineno = <optimized out>
        tmp_unused = <optimized out>
        exception_keeper_type_1 = 0x7f9c30cd7180
        exception_keeper_value_1 = 0x18c1500 <_Py_TrueStruct>
        exception_keeper_tb_1 = 0x7f9c1a149340
        exception_keeper_lineno_1 = <optimized out>
        exception_preserved_type_1 = <optimized out>
        exception_preserved_value_1 = <optimized out>
        exception_preserved_tb_1 = <optimized out>
        tmp_res = <optimized out>
        tmp_result = <optimized out>
        exception_keeper_type_2 = <optimized out>
        exception_keeper_value_2 = <optimized out>
        exception_keeper_tb_2 = <optimized out>
        exception_keeper_lineno_2 = <optimized out>
        exception_keeper_type_3 = <optimized out>
        exception_keeper_value_3 = <optimized out>
        exception_keeper_tb_3 = <optimized out>
        exception_keeper_lineno_3 = <optimized out>
        exception_keeper_type_4 = <optimized out>
        exception_keeper_value_4 = <optimized out>
        exception_keeper_tb_4 = 0x7f9c1a0ece70
        exception_keeper_lineno_4 = <optimized out>
        cache_frame_9f641251dfe286880f13a22251dc7153 = 0x7f9c1a15e8b0
        tmp_return_value = <optimized out>
        exception_keeper_type_5 = 0x7f9c1a15e8b0
        exception_keeper_value_5 = 0x7f9c1a0eed50
        exception_keeper_tb_5 = 0x7f9c1a0ece70
        exception_keeper_lineno_5 = <optimized out>
        tmp_condition_result_4 = <optimized out>
        tmp_compexpr_left_3 = <optimized out>
        tmp_compexpr_right_3 = <optimized out>
#22 0x000000000040a0d3 in CALL_FUNCTION_WITH_ARGS2 (called=0x7f9c1a0eb7c0, args=0x7ffc88b2b3d0) at __helpers.c:323
        function = <optimized out>
        result = 0x7ffc88b2b3d0
        pos_args = <optimized out>
        result = 0x7ffc88b2b3d0
#23 0x000000000040f46f in impl___main__$$$function_3_reproduce_bug (self=0x330e001, python_pars=0x7f9c18f4b030) at module.__main__.c:1904
        call_args = {0x7f9c1a0ec240, 0x7f9c313b4a70}
        tmp_called_name_3 = 0x330e001
        tmp_call_result_2 = 0x330e001
        tmp_args_element_name_2 = <optimized out>
        tmp_args_element_name_3 = 0x330e001
        var_canvas = 0x7f9c1a0fc800
        var_pb2 = 0x7f9c1a0ec240
        frame_58229ea95fe40dbb4e6b04f5d7c4e8f1 = <optimized out>
        type_description_1 = <optimized out>
        tmp_unused = <optimized out>
        exception_type = 0x2e6d140
        exception_value = 0x18b4de0 <meta_path_loader_entries>
        exception_tb = 0x7f9c315cd040
        exception_lineno = 418689072
        cache_frame_58229ea95fe40dbb4e6b04f5d7c4e8f1 = 0x7f9c1a0f01e0
        tmp_return_value = <optimized out>
        exception_keeper_type_1 = <optimized out>
        exception_keeper_value_1 = <optimized out>
        exception_keeper_tb_1 = <optimized out>
        exception_keeper_lineno_1 = <optimized out>
#24 0x0000000000da7255 in CALL_FUNCTION_NO_ARGS (called=0x7f9c1a0eb8b0) at /home/stas/.local/share/virtualenvs/segfault-gtk-caaKfl97/lib/python3.8/site-packages/nuitka/build/static_src/HelpersCalling.c:170
        function = <optimized out>
        result = 0x7f9c30ca6e50
#25 0x000000000041bb6d in modulecode___main__ (module=0x330e001, module_entry=0x7f9c18f4b030) at module.__main__.c:9562
        tmp_called_name_1 = 0x330e001
        tmp_call_result_2 = 0x330e001
        _init_done = true
        tmp_import_from_1__module = <optimized out>
        frame_b6392eee8e0396bdc61cb42e105e011c = 0x7f9c313b8040
        type_description_1 = <optimized out>
        tmp_unused = <optimized out>
        exception_type = 0x7f9c315cd040
        exception_value = 0x2e6d140
        exception_tb = 0x7f9c30ca6e50
        exception_lineno = 418689072
        exception_keeper_type_1 = <optimized out>
        exception_keeper_value_1 = <optimized out>
        exception_keeper_tb_1 = <optimized out>
        exception_keeper_lineno_1 = <optimized out>
#26 0x0000000000dd771c in loadModule (module=0x7f9c315cd040, module_name=0x7f9c31570c70, entry=0x18b4de0 <meta_path_loader_entries>) at static_src/MetaPathBasedLoader.c:873
        res = <optimized out>
        result = 0x330e001
#27 0x0000000000dd7d69 in _EXECUTE_EMBEDDED_MODULE (module=0x7f9c315cd040, module_name=0x7f9c31570c70, name=0xdd9f24 "__main__") at static_src/MetaPathBasedLoader.c:914
        entry = <optimized out>
        frozen_import = <optimized out>
        result = 0x18b4de0 <meta_path_loader_entries>
#28 0x0000000000409438 in main (argc=1052162176, argv=0x7f9c315e2cb0) at static_src/MainProgram.c:617
        ticker_value = 0x330e001 ""
        exit_code = 53534721
(gdb) 
